[package]
name = "worker-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql-client = { version = "0.34", default-features = false, features = ["workers_backend"] }
url = "2.5.0"
worker = "0.2.0"

[profile.release]
opt-level = "s" # optimize for size in release builds
lto = true
strip = true
codegen-units = 1

[patch.crates-io]
libsql-client = { git = "https://github.com/spigaz/libsql-client-rs" }
